### ISSUE TITLE
Cannot read property 'serialize' of undefined

### ISSUE THREAD

**Issue by purplecones** [jimah/atom-panels#1]
```
Error serializing package 'atom-panels' TypeError: Cannot read property 'serialize' of undefined
    at Object.module.exports.Splitter.serialize (/Users/xxx/.atom/packages/atom-panels/lib/panels.coffee:93:33)
    at Package.module.exports.Package.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:619:100)
    at PackageManager.module.exports.PackageManager.serializePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:596:63)
    at PackageManager.module.exports.PackageManager.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:589:14)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:771:38)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:984:27
```

I see these errors being thrown in the Atom console.

**Comment by dammitjim** [comment]
Hi purplecones,

I have published a fix to apm that I believe solves the problem, this is some unexpected behaviour due to some old, now unused, code.

If you are still having the issue after upgrading, please can you respond with information about your development environment :)

**Comment by purplecones** [comment]
Thanks, all good !
