### ISSUE TITLE
Uncaught TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by brandonparsons** [jimah/atom-panels#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-panels](https://github.com/jimah/atom-panels) package 0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'children' of undefined

```
At /Users/brandon/~.atom/packages/atom-panels/lib/panels.js:141

TypeError: Cannot read property 'children' of undefined
    at Object.getTargetPane (/packages/atom-panels/lib/panels.js:141:14)
    at Object.move (/packages/atom-panels/lib/panels.js:76:27)
    at /packages/atom-panels/lib/panels.js:44:50)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:07.9.0 intentions:highlight (input.hidden-input)
     -0:04.5.0 atom-panels:split-right (input.hidden-input)
```

### Non-Core Packages

```
atom-elixir 0.2.3 
atom-panels 0.4.1 
busy-signal 1.4.1 
elixir-alphabetize 0.3.0 
emmet 2.4.3 
git-plus 7.8.0 
indent-guide-improved 1.4.12 
intentions 1.1.2 
jumpy 3.1.3 
language-elixir 0.17.0 
linter 2.1.4 
linter-elixirc 1.6.0 
linter-ui-default 1.4.0 
phoenix-elixir-snippets 0.4.0 
set-syntax 0.3.2 
Sublime-Style-Column-Selection 1.7.4 
vim-mode-plus 0.92.1 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by Nitsorn** [comment]
+1 here, same issue

**Comment by bpwalford** [comment]
+1
